### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by reagle** [Galarius/pinotate#2]
Thanks for sharing this. I tried it for Aaron James's *Assholes: A Theory* and it crashes.

```
╰─➤  pinotate.py Assholes
Traceback (most recent call last):
  File "pinotate.py", line 37, in <module>
    main(args)
  File "pinotate.py", line 27, in main
    worker.export(args.title, args.out)
  File "/Users/reagle/bin/pinotate/core/worker.py", line 40, in export
    self.__export(book, out_dir)
  File "/Users/reagle/bin/pinotate/core/worker.py", line 55, in __export
    self.__save(title, highlights, out_dir)
  File "/Users/reagle/bin/pinotate/core/worker.py", line 59, in __save
    md = generate_md(title, highlights)
  File "/Users/reagle/bin/pinotate/core/utils.py", line 12, in generate_md
    text += '> {}\n\n'.format(highlight)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 173: ordinal not in range(128)
```

**Comment by Galarius** [comment]
@reagle, please tell me, what python version are you using to run `pinotate.py`?

**Comment by reagle** [comment]
Ah, if I run it with Python3 it doesn't have this problem. I should've known/guessed. Is there a reason you don't set it to 3?

```
#!/usr/bin/env python3
...
```

BTW: it doesn't output page numbers, but they appear in the screen of Books -- on Mac and iPad.

**Comment by Galarius** [comment]
> Is there a reason you don't set it to 3?

It seems, I just skipped it during update.

> BTW: it doesn't output page numbers, but they appear in the screen of Books -- on Mac and iPad.

Ok, I will try to dig it up from iBook's database.

**Comment by Galarius** [comment]
I've added requirement to use python3.

Pages are located in `ZANNOTATIONLOCATION` table in the calculable format [EPUB Canonical Fragment Identifier](http://idpf.org/epub/linking/cfi/epub-cfi.html), that looks like this `epubcfi(/6/6[item_GuidedTour]!/4[conceptual_flow_with_tasks]/2/2[chapter_container]/2/14/16/2/2/1:0)`. It doesn't make sense outside of epub book, because location is calculated using a number of factors (e.g. screen size and font size).
